// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FsBackTop: typeof import('./src/components/FsBackTop/FsBackTop.vue')['default']
    FsCodeCard: typeof import('./src/components/FsCodeCard/FsCodeCard.vue')['default']
    FsCodeMirror: typeof import('./src/components/FsCodeMirror/FsCodeMirror.vue')['default']
    FsCollectionCode: typeof import('./src/components/FsCollectionCode/FsCollectionCode.vue')['default']
    FsCommentCard: typeof import('./src/components/FsCommentCard/FsCommentCard.vue')['default']
    FsImage: typeof import('./src/components/FsImage/FsImage.vue')['default']
    FsMyComment: typeof import('./src/components/FsMyComment/FsMyComment.vue')['default']
    FsSearchBox: typeof import('./src/components/FsSearchBox/FsSearchBox.vue')['default']
    FsSideCard: typeof import('./src/components/FsSideCard/FsSideCard.vue')['default']
    FsSpaceCard: typeof import('./src/components/FsSpaceCard/FsSpaceCard.vue')['default']
    FsSwitch: typeof import('./src/components/FsSwitch/FsSwitch.vue')['default']
    FsTextEditor: typeof import('./src/components/FsTextEditor/FsTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
